name: GiftCode
main: HannesTheDev\Main
version: 1.0.0
api: 3.0.0
author: HannesTheDev

commands:
 gencode:
     description: Generate a giftcode
     permission: gencode.command
 redeem:
     description: Redeem a giftcode

permissions:
 gencode.command:
     description: /gencode permission
     default: op